language: python
before_install:
  - export FIREFOX_SOURCE_URL='https://download.mozilla.org/?product=firefox-latest&lang=fr&os=linux64'
  - wget --no-verbose -O /tmp/firefox-latest.tar.bz2 $FIREFOX_SOURCE_URL
  - tar -xjf /tmp/firefox-latest.tar.bz2
  - export PATH=$PWD/firefox:$PATH
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.19.2
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - pip install -r requirements/requirements.txt
  - pip install -r requirements/requ-testing.txt
  - yarn
  - ls -al libreosteoweb/static/components/moment/
  - ls -al libreosteoweb/static/components/moment/meteor/
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v0.21.0-linux64.tar.gz -O /tmp/geckodriver.tar.gz
  - tar -xvf /tmp/geckodriver.tar.gz
  - export PATH=$PATH:$PWD
  - python ./manage.py collectstatic --no-input
python:
  - "3.6"
branches:
  - develop
  - master
env:
  - MOZ_HEADLESS=1

before_script:
  - python ./server.py &
  - sleep 3
script:
  - echo 'Do unit tests pass ?'
  - python ./manage.py test

  - echo 'Do functional tests pass ?'
  - xvfb-run --server-args="-screen 0 1024x768x24" robot tests

  - echo 'Are translations in clean state, with no string forgotten ?'
  - python ./manage.py makemessages -d django --no-location ; python ./manage.py makemessages --no-location -d djangojs ; git diff --exit-code -G'^[^"]'

  - echo 'Did you forgot some migration ?'
  - python ./manage.py makemigrations --check
